Round 9
Basystyy/testguru pull request #8
Opened 2024-04-05 07:17 UTC by Basystyy

2024-06-11 12:09 UTC, d1ma-angel approved these changes

2024-06-11 12:09 UTC, d1ma-angel commented on app/models/test_passage.rb
> +  def test_completed?
Лучше `.passed_successfully?`, a то у тебя получается два `.completed?`

2024-06-11 12:09 UTC, d1ma-angel commented on app/models/test_passage.rb
> +    correct_questions >= (test.questions.count.to_f * 85 / 100)
На данный момент это мелочи, но потом уже на работе узнаешь одну важную вещь: если можно оперировать целыми числами и не уходить в дробные, то лучше так и сделать. Особенно это касается валюты.

2024-06-11 12:09 UTC, d1ma-angel commented on app/models/test_passage.rb
> +  def correct_answer?(answer_ids)
У тебя там в задании есть подсказка как сделать это проще и понятнее. Лучше заменить.

2024-06-12 09:39 UTC, Basystyy commented on app/models/test_passage.rb
> +  def test_completed?
исправлено

2024-06-12 09:56 UTC, Basystyy commented on app/models/test_passage.rb
> +    correct_questions >= (test.questions.count.to_f * 85 / 100)
испралено

2024-06-12 10:36 UTC, Basystyy commented on app/models/test_passage.rb
> +  def correct_answer?(answer_ids)
исправлено

2024-06-12 10:48 UTC, d1ma-angel requested changes

2024-06-12 10:48 UTC, d1ma-angel commented on app/models/test_passage.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort || answer_ids != nil
`|| answer_ids != nil` вот это не очень понял
если я правильно могу прочесть код, то, получается, он тебе всегда будет true возвращать если хоть что-то в него прилетело
```
[1, 2] == [5] || ['5'] != nil
false || true
=> true
```

2024-06-12 10:48 UTC, d1ma-angel commented on app/models/test_passage.rb
> +    (correct_questions.to_f * 100).floor.to_i >= (test.questions.count.to_f * 85).floor.to_i
`correct_questions * 100 >= test.questions.count * 85`

2024-06-15 12:59 UTC, Basystyy commented on app/models/test_passage.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort || answer_ids != nil
Пардон, это до варианта с return false попытка была, забыл убрать

2024-06-15 13:15 UTC, merged